cob_x_offset_m: -0.025
cob_y_offset_m: 0
hip_roll_swap_angle_rad: 0
foot_roll_gyro_p_gain: 0.37
foot_roll_gyro_d_gain: 0
foot_pitch_gyro_p_gain: 0.15
foot_pitch_gyro_d_gain: 0
foot_roll_angle_p_gain: 0.38
foot_roll_angle_d_gain: 0
foot_pitch_angle_p_gain: 0.14
foot_pitch_angle_d_gain: 0
foot_x_force_p_gain: 0.01
foot_x_force_d_gain: 0
foot_y_force_p_gain: 0.01
foot_y_force_d_gain: 0
foot_z_force_p_gain: 0.01
foot_z_force_d_gain: 0
foot_roll_torque_p_gain: 0.0125
foot_roll_torque_d_gain: 0
foot_pitch_torque_p_gain: 0.01
foot_pitch_torque_d_gain: 0
roll_gyro_cut_off_frequency: 45
pitch_gyro_cut_off_frequency: 40
roll_angle_cut_off_frequency: 45
pitch_angle_cut_off_frequency: 40
foot_x_force_cut_off_frequency: 40
foot_y_force_cut_off_frequency: 40
foot_z_force_cut_off_frequency: 40
foot_roll_torque_cut_off_frequency: 40
foot_pitch_torque_cut_off_frequency: 40
updating_duration: 1