########################################
#  example  # for ROBOTIS framework    #
#  joint num : joint name              #
#  1 : l_hip_yaw                       #
#  2 : r_knee_pitch                    #
########################################
joint_data:
  19 : l_ankle_pitch 
  21 : l_ankle_roll
  11 : l_hip_pitch
  13 : l_hip_roll
  15 : l_hip_yaw
  17 : l_knee_pitch
  20 : r_ankle_pitch
  22 : r_ankle_roll
  12 : r_hip_pitch
  14 : r_hip_roll
  16 : r_hip_yaw
  18 : r_knee_pitch



