updating_duration: 1.5

cob_x_offset_m: 0
cob_y_offset_m: 0

foot_roll_gyro_p_gain: 0
foot_roll_gyro_d_gain: 0 

foot_pitch_gyro_p_gain: 0.04
foot_pitch_gyro_d_gain: 0

foot_copFz_p_gain: 0.012
foot_copFz_d_gain: 0
