default_step_num: 4
default_step_length: 0.25
default_side_step_length: 0.1
default_step_angle_radian: 0.05
default_step_time: 0.85
expanded_step_num: 4
expanded_step_length: 0.1
expanded_side_step_length: 0.05
expanded_step_angle_radian: 0.3
expanded_step_time: 0.85
centered_step_num: 4
centered_step_length: 0.05
centered_side_step_length: 0.1
centered_step_angle_radian: 0.3
centered_step_time: 0.85
foot_step_dsp: 0.15
foot_step_foot_z_swap: 0.08
foot_step_body_z_swap: 0.01
foot_step_y_zmp_conv: -0.02