default_step_num: 2
default_step_length: 0.08
default_side_step_length: 0.06
default_step_angle_radian: 0.1
default_step_time: 5
expanded_step_num: 1
expanded_step_length: 0.07000000000000001
expanded_side_step_length: 0.05
expanded_step_angle_radian: 0.3
expanded_step_time: 5
centered_step_num: 1
centered_step_length: 0.02
centered_side_step_length: 0.05
centered_step_angle_radian: 0.3
centered_step_time: 5
foot_step_dsp: 0.4
foot_step_foot_z_swap: 0.065
foot_step_body_z_swap: 0
foot_step_y_zmp_conv: -0.032

